# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [1]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
# np.savetxt('data.txt', data)    # 공백으로 구분
np.savetxt('data.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('data.txt', delimiter=",")
print(load_data)

[[0.56198629 0.93667764 0.09380274]
 [0.91831709 0.70613658 0.50432116]
 [0.99216162 0.45446337 0.20375002]
 [0.48490427 0.06172789 0.19848284]
 [0.83766151 0.66965416 0.72140103]]
[[0.56198629 0.93667764 0.09380274]
 [0.91831709 0.70613658 0.50432116]
 [0.99216162 0.45446337 0.20375002]
 [0.48490427 0.06172789 0.19848284]
 [0.83766151 0.66965416 0.72140103]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [5]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
if not os.path.exists('../generated'):
    os.makedirs('../generated')
np.save('../generated/data', data)

load_data = np.load('../generated/data.npy')
print("load_data :\n", load_data)

data :
 [[0.31028259 0.94733507 0.93687383]
 [0.36586245 0.62353959 0.54098976]
 [0.62025692 0.31330371 0.34397674]
 [0.14246396 0.65600572 0.69070346]
 [0.67251363 0.6363734  0.55643979]]
load_data :
 [[0.31028259 0.94733507 0.93687383]
 [0.36586245 0.62353959 0.54098976]
 [0.62025692 0.31330371 0.34397674]
 [0.14246396 0.65600572 0.69070346]
 [0.67251363 0.6363734  0.55643979]]
