# Numpy
-----
## 02. Numpy 배열
### 다차원 배열 개념
### 배열 생성 방법
- 리스트, 튜플을 활용한 배열 생성

In [1]:
import numpy as np

# 파이썬 기본 리스트
lst1 = [1, 2, 3, 4, 5]   
print(lst1, type(lst1))
# 파이썬 튜플
tpl = 1, 2, 3, 4, 5    
print(tpl, type(tpl))

# 리스트를 이용한 넘파이 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])    
print(arr1, type(arr1))
# 튜플을 이용한 넘파이 배열 생성
arr2 = np.array((1, 2, 3, 4, 5))    
print(arr2, type(arr2))

[1, 2, 3, 4, 5] <class 'list'>
(1, 2, 3, 4, 5) <class 'tuple'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>


- 범위 배열 생성

In [1]:
import numpy as np

# 0부터 10 이전까지
lst = range(10) 
print(lst)
arr = np.arange(10)
print(arr)

# 2부터 10 이전까지
lst2 = range(2, 10) 
print(lst2)
arr2 = np.arange(2, 10)
print(arr2)

# 0부터 10 이전까지 2간격으로
lst3 = range(0, 10, 2)  
print(lst3)
arr3 = np.arange(0, 10, 2)
print(arr3)

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]
range(2, 10)
[2 3 4 5 6 7 8 9]
range(0, 10, 2)
[0 2 4 6 8]


- 배열 함수를 이용한 배열의 생성

In [3]:
import numpy as np
# 영행렬
zeros3 = np.zeros(3) 
print(zeros3)
zeros3x3 = np.zeros((3, 3))
print(zeros3x3)
# 모든 원소가 1인 행렬
ones3 = np.ones(3)
print(ones3)
ones3x3 = np.ones((3, 3))
print(ones3x3)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- 단위행렬 만들기
    - 단위행렬 : 주대각선 상의 원소가 모두 1이고, 나머지 원소는 모두 0인 정사각형 행렬

In [2]:
import numpy as np

# 단위항렬 : eye
eye = np.eye(3) #   3x3의 행렬에서 주대각선상의 원소가 모두 1인 행렬
print("3x3 단위행렬:\n", eye)

eye2 = np.eye(3, k=-1)  # k: 주 대각선을 위, 아래로 얼마나 이동시킬 것인지 결정
print(eye2)


3x3 단위행렬:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


- 난수를 이용한 배열 생성
    - 균일분포 난수 배열 생성 : rand()
    - 정규분포 난수 배열 생성 : randn()
    - 정수형 난수 생성 : randint()

In [3]:
import numpy as np

# 균일분포 난수 배열
uni_rand = np.random.rand(4, 3)
print(uni_rand)
# 정규분포 난수 배열
norm_rand = np.random.randn(4, 3)
print(norm_rand)
# 정수 난수 배열
int_rand = np.random.randint(1, 10, size=(4, 3))
print(int_rand)

[[0.77700349 0.51575022 0.23000207]
 [0.3774291  0.83134691 0.46293803]
 [0.82569243 0.17846065 0.32798722]
 [0.72121289 0.88640947 0.48609921]]
[[-1.56417197  0.03938063 -0.29036536]
 [-1.48391993  1.23801293  0.06274622]
 [ 0.358974    0.07506571 -0.61042739]
 [-1.39317496 -0.88665298  0.31345209]]
[[8 2 9]
 [9 4 2]
 [2 4 4]
 [3 5 8]]


- 확률 분포를 이용한 난수 배열 생성
    - 균등분포 난수 : uniform()
    - 정규분포 난수 : normal()
    - 지수분포 난수 : exponential()

In [6]:
import numpy as np

# 균등분포 난수
uni_rand = np.random.uniform(1, 6, size=(4, 3))
print(uni_rand)
# 정규분포 난수
norm_rand = np.random.normal(loc=0.0, scale=1.0, size=(4, 3))
print(norm_rand)
# 지수분포 난수
exp_rand = np.random.exponential(scale=1., size=(4,3))
print(exp_rand)

[[4.84081529 2.77503012 3.65732551]
 [3.1477674  3.78732817 4.87515582]
 [5.47184613 2.30783933 4.84684013]
 [2.18311657 4.07448024 1.358911  ]]
[[-0.8465125  -0.35656578 -0.81672656]
 [ 0.17916991 -0.05887039  0.03217854]
 [-0.15778508  1.29642564  1.59548217]
 [-0.10975417  0.28804148  0.28398755]]
[[0.25044935 0.62062665 0.8710231 ]
 [0.71281168 0.2327274  0.7185806 ]
 [0.21691047 0.69930073 1.53571382]
 [0.07251541 0.81051954 1.90275819]]


- 난수 행렬 만들 때 시드의 지정
    - seed()

In [7]:
import numpy as np

# 일반적인 난수의 사용
for i in range(10):
    print(np.random.randint(1, 7), end=", ")
else:
    print()
    
# seed 설정을 이용한 재현성의 확보
for i in range(10):
    np.random.seed(42)
    print(np.random.randint(1, 7), end=", ")

3, 5, 5, 2, 4, 5, 5, 4, 6, 6, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

### 배열의 속성과 모양

In [8]:
import numpy as np

# 파이썬의 기본 리스트
# lst = [42, 3.14, True, "python", [1, 2, 3, 4, 5]]
lst = [42, 3.14, True, "python"]
print([type(o) for o in lst])

# 넘파이 배열
arr = np.array(lst)
print(arr)

[<class 'int'>, <class 'float'>, <class 'bool'>, <class 'str'>]
['42' '3.14' 'True' 'python']


- 배열의 속성
    - shape : 배열의 형상 (행의 개수, 열의 개수)
    - ndim : 배열의 차원. 배열의 축(axis)의 개수
    - size : 배열의 전체 원소 개수
    - dtype : 배열의 데이터 타입
        - https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [9]:
import numpy as np

# 0 ~ 9 사이의 난수를 가진 4행 3열 배열 생성
arr = np.random.randint(0, 10, size=(4, 3))
# 배열의 속성을 알아봅시다
print("형상:", np.shape(arr), arr.shape)
print("차원:", np.ndim(arr), arr.ndim)
print("원소 개수:", np.size(arr), arr.size)
print("데이터 타입:", arr.dtype)

형상: (4, 3) (4, 3)
차원: 2 2
원소 개수: 12 12
데이터 타입: int32


### 배열의 인덱싱과 슬라이싱
- 파이썬 순차자료형의 인덱싱과 슬라이싱 규칙이 그대로 적용

In [10]:
import numpy as np

arr = np.array([
    [0, 1, 2, 3, 4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
])
print(arr)

# 이 배열에 대해 정보를 캐내 보자
print("형태:", arr.shape)
print("차원:", arr.ndim)
print("크기:", arr.size)
print("데이터 타입:", arr.dtype)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
형태: (5, 5)
차원: 2
크기: 25
데이터 타입: int32


In [11]:
# 3행 2열의 데이터는 무엇인가?
print(arr[3, 2])
print()
# 2행 전체의 데이터를 추출해 보자
print(arr[2])
print()
# 2열 전체의 데이터를 추출해 보자
print(arr[:, 2])
print()
# 1행 1열 ~ 3행 3열의 데이터를 추출해 보자
print(arr[1:4, 1:4])

32

[20 21 22 23 24]

[ 2 12 22 32 42]

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### 브로드캐스팅
- 다른 형상(Shape)을 가지 배열들 간에 산술연산을 수행할 때, 자동으로 형상을 맞춰주는 기능

- 브로드캐스팅의 규칙
    - 두 배열의 뒷 차원(오른쪽에서 왼쪽으로)부터 비교, 차원의 크기가 같거나 둘 중의 하나의 차원이 1인 경우 브로드캐스팅이 가능
    - 브로드캐스팅은 해당 차원의 크기를 1인 차원과 동일한 크기로 간주하여 진행
        
- 브로드캐스팅은 배열의 형상을 맞추는 작업을 자동으로 수행하기 때문에 코드를 간결하게 작성할 수 있고, 많은 경우에 유용하게 활용
    - 그러나 항상 배열의 형상 변화에 주의해야 하고, 브로드캐스팅 규칙을 잘 이해하고 사용하는 것이 중요

In [12]:
import numpy as np

# 1차원 배열과 0차원 데이터의 연산
arr1 = np.array([1, 2, 3])
arr2 = 2

result = arr1 + arr2    # should be [3, 4, 5]
print(result)

# 다차원 배열간의 브로드캐스팅
arr3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr4 = np.array([7, 8, 9])

result = arr3 + arr4
print(result)

arr5 = np.array([7, 8, 9, 10])  # Error
result = arr3 + arr5
print(result)

[3 4 5]
[[ 8 10 12]
 [11 13 15]]


ValueError: operands could not be broadcast together with shapes (2,3) (4,) 